import {
  Activity,
  AlertTriangle,
  Bell,
  BookOpen,
  Boxes,
  CheckCircle2,
  ClipboardCheck,
  ClipboardList,
  Clock,
  FileBarChart,
  Inbox,
  LayoutDashboard,
  Megaphone,
  Package,
  PackageCheck,
  Scale,
  Search,
  Share2,
  ShieldCheck,
  Sprout,
  Store,
  Truck,
  Users,
  Wallet,
  type LucideIcon,
} from 'lucide-react'

const PETA: Record<string, LucideIcon> = {
  Activity,
  AlertTriangle,
  Bell,
  BookOpen,
  Boxes,
  CheckCircle2,
  ClipboardCheck,
  ClipboardList,
  Clock,
  FileBarChart,
  Inbox,
  LayoutDashboard,
  Megaphone,
  Package,
  PackageCheck,
  Scale,
  Search,
  Share2,
  ShieldCheck,
  Sprout,
  Store,
  Truck,
  Users,
  Wallet,
}

export function Ikon({ nama, className }: { nama: string; className?: string }) {
  const Komponen = PETA[nama] ?? LayoutDashboard
  return <Komponen className={className} aria-hidden strokeWidth={1.9} />
}
